baseURL: https://jamiecollinson.com
theme: jc
disablePathToLower: true
languageCode: en-us
title: Jamie Collinson
googleAnalytics: UA-3143424-7
permalinks:
  post: /blog/:filename
publishDir: docs
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: friendly
FootnoteReturnLinkContents: "<sup>↩</sup>"
enableRobotsTXT: true
ignoreFiles:
  - '.*flycheck_.*'