baseURL: https://jamiecollinson.com
theme: minimal100
disablePathToLower: true
languageCode: en-us
title: Jamie Collinson
permalinks:
  post: /blog/:filename
publishDir: docs
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: friendly
FootnoteReturnLinkContents: "<sup>↩</sup>"
enableRobotsTXT: true
ignoreFiles:
  - '.*flycheck_.*'