baseURL: https://jamiecollinson.com
theme: jc
disablePathToLower: true
languageCode: en-us
title: Jamie Collinson
permalinks:
  post: /blog/:contentbasename
publishDir: docs
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: false
    style: friendly
FootnoteReturnLinkContents: "<sup>↩</sup>"
enableRobotsTXT: true
ignoreFiles:
  - '.*flycheck_.*'
