#+title: Blogging with org - test page
#+date: Sun Nov 12 13:28:25 2017

Can there be anything more satisfying than blogging in emacs, the world's greatest text editor?

** This is a heading

There are many things to like about writing a heading such as this in emacs. For a start it's beautifully presented. Also it is older than I am.[fn:1]

#+BEGIN_SRC js 
  var test = "whatever";
#+END_SRC

#+BEGIN_SRC python
  def my_function(y):
      """This is a python function"""
      return [x for x in y if y % 2 == 0]
#+END_SRC

Now I wonder if I'd like to go to the pub, it has been a tiring afternoon afterall.

This is another paragraph of text saying somethig insiteful.

*** And a sub-sub heading

This is some content on a sub-sub heading.

/Doing a test of some italic text - I need a load of text here and it doesn't really matter what it says as long as it fills some space and doesn't look too wrong./

*** And another

Wow this is deep!

** This is a subheading

Headings need subheadings too.[fn:2]

Can I type normally and have it update? Yes I can![fn:3]

[fn:1] testing out yet another footnote, this is a much longer footnote to check behaviour when there is more text.

[fn:2] testing footnotes. lorem ipsum dolor sit amet, etc. etc.

[fn:3] test again
